### ISSUE TITLE
[BUG] Shuffle button not visible with new UI version

### ISSUE THREAD

**Issue by Autounit777** [NikkelM/Random-YouTube-Video#280]
The Random button does not appear in the place where it used to appear... Help fix the Google Chrome browser Windows eleven

**Comment by NikkelM** [comment]
Hi @Autounit777, thanks for the report. I can't reproduce this on my end at the moment. Could you share the unique URL of your browser after visiting this URL: https://www.whatismybrowser.com/ as well as a screenshot of how the channel/video page looks like where you can't see the button? Does the button not appear on channel, video and shorts pages?
In the meanwhile - there is a shuffle button in the extension popup that can always be used.

**Comment by Autounit777** [comment]
https://whatismybrowser.com/w/763A5MH

![Снимок экрана (107)](https://github.com/NikkelM/Random-YouTube-Video/assets/121161095/2e2e7262-bbb8-4367-a724-e64713c5be93)
![Снимок экрана (107)](https://github.com/NikkelM/Random-YouTube-Video/assets/121161095/a5eeb954-5fcd-4139-bb73-4b4dc4ac44b9)

**Comment by Autounit777** [comment]
The situation has not changed.
Everything worked fine before
please help

**Comment by NikkelM** [comment]
Thanks @Autounit777 for the details. From your screenshot it looks like you have a newer version of the YouTube UI, YouTube regularly updates the UI for only some users at a time. Since I don't have this new layout yet, I can't fix the problem on my own. What you could do to help me is the following, which will allow me to see the logic behind the new UI:

1. Go to a channel page.
2. As it looks like you are on Windows and Chrome, press `F12` to open the browser's inspector tool. If that doesn't work, right-click on the page and use `Inspect`.
3. Navigate to the `Elements` tab on the panel that opens and right-click on the `<html style...` element on top, as shown below:
![image](https://github.com/NikkelM/Random-YouTube-Video/assets/57323886/85a4434a-69ea-48da-bcdd-2f44f4a671c9)
4. Click `Edit as HTML`.
5. Use `Ctrl + a` to select all text in the textbox, then `Ctrl + c` to copy it.
6. Open any text-editing program (for example, Notepad) and paste the text using `Ctrl + v`, save the file to your computer, then upload it in a comment here.
7. Optional: If you also cannot see the button on video pages, do the same steps as above again, but for a video page instead of a channel page.

This will allow me to see what has changed with the structure of the YouTube pages, and why the button cannot be added anymore.
If you're not able or don't want to do the above, you will unfortunately need to wait until I can reproduce this.
You can also always use the shuffle button in the popup, which should still update with the current channel you're viewing. You can also try using a different browser, which might not yet have the new UI.

**Comment by Autounit777** [comment]
https://dropmefiles.com/PbPWV

file txt

**Comment by NikkelM** [comment]
Thanks for the file @Autounit777. I checked the contents and don't see anything that would conflict with the extension. The only other reason for the button to not appear that I can thank of would be that the browser events YouTube sends when you navigate the page have changed in your version.
Could you check if the shuffle button in the popup still works, meaning that it still correctly updates the name of the channel you last visited? If that does not get updated, then there is a problem with the events and we might be able to investigate that further.

**Comment by Autounit777** [comment]
thank you so much for your support !  I don’t know what you did, But you did it! Everything works Thank you.

**Comment by NikkelM** [comment]
Thanks for letting me know @Autounit777 - I'm very happy it works for you again, but there weren't any changes in the extension that should have fixed this - did the YouTube UI change again perhaps?

**Comment by NikkelM** [comment]
@Autounit777 I have today been able to reproduce the issue and created a fix. This should be rolled out to the various extension stores in the next days.

**Comment by Autounit777** [comment]
You are a great master of your craft.  Thank you for this, I'm a big fan of random events and have been looking for an app like this for a long time.  Thank you for that.
