### ISSUE TITLE
[BUG] I just installed the Random YouTube video plugin, but the shuffle button doesn't show up on the channel I just went to. Is there a step I missed when installing the plugin?

### ISSUE THREAD

**Issue by Crazytrain2015** [NikkelM/Random-YouTube-Video#83]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
3. See error

**Expected behaviour**

**Screenshots**

**Software information(please complete the following information):**
 - Extension Version [e.g. 0.0.2]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:

**Additional context**

**Comment by Crazytrain2015** [comment]
Here is a screenshot of where the button was supposed to show up
![Skärmbild 2023-02-02 102650](https://user-images.githubusercontent.com/124250687/216284978-50f8dd2d-8d4f-49ba-b87e-346702ea80a9.png)

**Comment by NikkelM** [comment]
Hi @Crazytrain2015, you did everything correctly, there is no additional setup necessary. However, it looks to me like your YouTube has an older layout/theme (which can be seen on e.g. the button styling) than the current default.
It's likely that the extension simply didn't find the necessary element on the website that it uses to insert the button, as these elements are named differently in older layouts. 

Depending on how difficult it is, I could try to add support for older versions, but I would need some information from you to replicate this for myself:

- Which browser (use [whatismybrowser](https://www.whatismybrowser.com/) if you are unsure) and operating system you are using? It's possible that YouTube doesn't load the new layout for older browser versions due to performance reasons.
- Also, there are extensions that revert YouTube to the old layout - are you by any chance using one of those?

For reference, this is how it looks in the current YouTube layout:
![image](https://user-images.githubusercontent.com/57323886/216306626-92348e1e-95b1-4682-adf3-6c164a3acbf3.png)

**Comment by Crazytrain2015** [comment]
I am using Chrome 109 on Windows 10, I am not using any extensions that
revert the YouTube layout.
Here is the link to my whatismybrowser
https://whatismybrowser.com/w/RG3SL7M

Den tors 2 feb. 2023 kl 12:08 skrev Nikkel Mollenhauer <
***@***.***>:

**Comment by NikkelM** [comment]
Thanks for the info. From your browser information I see no reason why your YouTube would still be displayed in the old layout, this is very weird behaviour.

If you're willing to try, I would suggest to test how the website looks (i.e., if the layout is updated) when you use a different browser - for compatibility with the extension you could try Microsoft Edge (as you can add Chrome extensions to Edge as well) and see if the layout is the new one there. Alternatively, you could also check if anything changes when you open YouTube in a private session window.

I assume the button also does not show when you are playing a video? It should appear next to the subscribe button on video pages as well.

**Comment by Crazytrain2015** [comment]
Alright thank you, it works on Edge

**Comment by NikkelM** [comment]
Okay, interesting, I'm glad you at least have a way to get it working now. Did you also try clearing the cookies on Chrome, or does it still have the old layout there as well after doing that?

**Comment by Crazytrain2015** [comment]
I will try that.

Den tors 2 feb. 2023 21:58Nikkel Mollenhauer ***@***.***>
skrev:

**Comment by NikkelM** [comment]
I'm closing this for now, as it seems that you were able to resolve the problem.
